name: main
on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@v1
      with:
        go-version: 1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        make go.get

    - name: Build binaries
      run: |
        make windows darwin linux

    - name: Set up Docker
      uses: docker/setup-docker-action@v4
      with:
        daemon-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          }

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        load: true
        tags: ghcr.io/arnisoph/postisto/linux:buildtestonly
        push: false


  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v1
        with:
          go-version: 1.22
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          make go.get

#      - name: setup integration env
#        run: |
#          docker run -d --name dovecot -p 10143:143 -p 10993:993 -p 6379:6379 bechtoldt/tabellarius_tests-docker

      - name: go test
        env:
          POSTISTO_GMAIL_TEST_ACC_USERNAME: ${{ secrets.POSTISTO_GMAIL_TEST_ACC_USERNAME }}
          POSTISTO_GMAIL_TEST_ACC_PASSWORD: ${{ secrets.POSTISTO_GMAIL_TEST_ACC_PASSWORD }}
        run: |
          make go.test

      - name: upload code coverage
        env: # Or as an environment variable
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash)
